### 게시물 목록 조회
GET /api/board/list
Host: localhost:8080
Content-Type: application/json

### 게시물 조회
GET /api/board/1
Host: localhost:8080
Content-Type: application/json

### 게시물 등록
POST /api/board/write HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "title" : "title{{$randomInt}}",
  "content" : "{{$random.alphanumeric(10)}}",
  "regType" : "User",
  "regName" : "name{{$randomInt}}"
}

### 게시물 수정
PUT /api/board/3 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "title" : "title{{$randomInt}}",
  "content" : "{{$random.alphanumeric(20)}}"
}

### 게시물 삭제
DELETE /api/board/8 HTTP/1.1
Host: localhost:8080
Content-Type: application/json